# -*- coding: utf-8 -*-
"""Resnet18Distillation.ipynb

Automatically generated by Colab.

"""

pip install torch torchvision numpy matplotlib scikit-learn

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision import models, datasets, transforms
from torch.utils.data import DataLoader
import time
import numpy as np
import matplotlib.pyplot as plt

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
])

train_dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=2)

print(f'Train batches: {len(train_loader)}, Test batches: {len(test_loader)}')

parent = models.resnet18(pretrained=True)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
parent.eval()

dummy_input = torch.randn(128, 3, 224, 224)
output = parent(dummy_input)
print(output)

# Define student model (half-width ResNet18)
class BasicBlock(nn.Module):
    expansion = 1

    def __init__(self, in_channels, out_channels, stride=1):
        super(BasicBlock, self).__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_channels)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(out_channels)
            )

    def forward(self, x):
        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)
        out = self.conv2(out)
        out = self.bn2(out)
        out += self.shortcut(x)
        out = self.relu(out)
        return out

class StudentResNet18(nn.Module):
    def __init__(self, num_classes=10):
        super(StudentResNet18, self).__init__()
        self.in_channels = 32

        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(32)
        self.relu = nn.ReLU(inplace=True)

        self.layer1 = self._make_layer(BasicBlock, 32, 2, stride=1)
        self.layer2 = self._make_layer(BasicBlock, 64, 2, stride=2)
        self.layer3 = self._make_layer(BasicBlock, 128, 2, stride=2)
        self.layer4 = self._make_layer(BasicBlock, 256, 2, stride=2)

        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(256, num_classes)

    def _make_layer(self, block, out_channels, num_blocks, stride):
        strides = [stride] + [1] * (num_blocks - 1)
        layers = []
        for stride in strides:
            layers.append(block(self.in_channels, out_channels, stride))
            self.in_channels = out_channels
        return nn.Sequential(*layers)

    def forward(self, x):
        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        out = self.layer4(out)

        out = self.avgpool(out)
        out = out.view(out.size(0), -1)
        out = self.fc(out)
        return out

student = StudentResNet18(num_classes=10).to(device)
print(f'Student model created. Parameters: {sum(p.numel() for p in student.parameters()):,}')

# Load teacher model (pretrained ResNet18, modified for CIFAR-10)
teacher = models.resnet18(pretrained=True)
num_ftrs = teacher.fc.in_features
teacher.fc = nn.Linear(num_ftrs, 10)
teacher.to(device)
teacher.eval()

print(f'Teacher model created. Parameters: {sum(p.numel() for p in teacher.parameters()):,}')

# Distillation training loop
def train_distillation(student, teacher, train_loader, test_loader, epochs=10, temperature=4.0, alpha=0.5):
    optimizer = optim.SGD(student.parameters(), lr=0.15, momentum=0.9, weight_decay=5e-4)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=7, gamma=0.1)

    train_losses = []
    train_accs = []
    test_accs = []

    for epoch in range(epochs):
        student.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for batch_idx, (inputs, labels) in enumerate(train_loader):
            inputs, labels = inputs.to(device), labels.to(device)

            # Get teacher outputs (no gradients)
            with torch.no_grad():
                teacher_logits = teacher(inputs)

            # Get student outputs
            student_logits = student(inputs)

            # Compute distillation loss
            ce_loss = F.cross_entropy(student_logits, labels)
            kl_loss = F.kl_div(
                F.log_softmax(student_logits / temperature, dim=1),
                F.softmax(teacher_logits / temperature, dim=1),
                reduction='batchmean'
            )
            loss = alpha * ce_loss + (1 - alpha) * kl_loss

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            _, predicted = student_logits.max(1)
            correct += predicted.eq(labels).sum().item()
            total += labels.size(0)

        train_loss = running_loss / len(train_loader.dataset)
        train_acc = 100.0 * correct / total
        train_losses.append(train_loss)
        train_accs.append(train_acc)

        # Validation
        student.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for inputs, labels in test_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = student(inputs)
                _, predicted = outputs.max(1)
                correct += predicted.eq(labels).sum().item()
                total += labels.size(0)

        test_acc = 100.0 * correct / total
        test_accs.append(test_acc)

        scheduler.step()

        print(f'Epoch {epoch+1}/{epochs} | Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}% | Test Acc: {test_acc:.2f}%')

    return train_losses, train_accs, test_accs

# Train
print('Starting distillation training...')
train_losses, train_accs, test_accs = train_distillation(
    student=student,
    teacher=teacher,
    train_loader=train_loader,
    test_loader=test_loader,
    epochs=10,
    temperature=4.0,
    alpha=0.5
)
print('Training complete.')

# Profiling
def get_model_size(model):
    param_size = 0
    for param in model.parameters():
        param_size += param.nelement() * param.element_size()
    buffer_size = 0
    for buffer in model.buffers():
        buffer_size += buffer.nelement() * buffer.element_size()
    return (param_size + buffer_size) / (1024 ** 2)

# Inference latency
student.eval()
teacher.eval()

test_batch = next(iter(test_loader))
test_input = test_batch[0][:1].to(device)  # Take first image
num_inferences = 100

# Warm up
for _ in range(10):
    with torch.no_grad():
        _ = student(test_input)
        _ = teacher(test_input)

# Profile student
student_times = []
with torch.no_grad():
    for _ in range(num_inferences):
        torch.cuda.synchronize()
        start = time.perf_counter()
        _ = student(test_input)
        torch.cuda.synchronize()
        end = time.perf_counter()
        student_times.append((end - start) * 1000)

# Profile teacher
teacher_times = []
with torch.no_grad():
    for _ in range(num_inferences):
        torch.cuda.synchronize()
        start = time.perf_counter()
        _ = teacher(test_input)
        torch.cuda.synchronize()
        end = time.perf_counter()
        teacher_times.append((end - start) * 1000)

student_latency = np.mean(student_times)
teacher_latency = np.mean(teacher_times)
student_size = get_model_size(student)
teacher_size = get_model_size(teacher)

torch.save(student.state_dict(), 'student_distilled.pth')
print('Model saved to student_distilled.pth')

print('\n=== RESULTS ===')
print(f'Student Model Latency: {student_latency:.4f} ms')
print(f'Teacher Model Latency: {teacher_latency:.4f} ms')
print(f'Speedup: {teacher_latency / student_latency:.2f}x')
print(f'Student Model Size: {student_size:.2f} MB')
print(f'Teacher Model Size: {teacher_size:.2f} MB')
print(f'Size Reduction: {teacher_size / student_size:.2f}x')
print(f'Final Test Accuracy: {test_accs[-1]:.2f}%')

# Plot results

models = ['Student (Parameters: 2,797,610)', 'Teacher (Parameters: 11,181,642)']
sizes = [10.69, 42.69]
colors = ['#2ecc71', '#e74c3c']

plt.figure(figsize=(6, 4))
bars = plt.bar(models, sizes, color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)

plt.ylabel('Model Size (MB)', fontsize=12)
plt.title('Model Size Comparison (MB): Knowledge Distillation', fontsize=14, fontweight='bold')
plt.ylim(0, 50)

for bar, size in zip(bars, sizes):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
             f'{size:.2f} MB',
             ha='center', va='bottom', fontsize=11, fontweight='bold')

reduction = 42.69 / 10.69
plt.text(0.5, 45, f'{reduction:.2f}x reduction',
         ha='center', fontsize=12, fontweight='bold',
         bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.3))

plt.tight_layout()
plt.savefig('model_size_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print()

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 2)
plt.plot(train_accs, label='Train')
plt.plot(test_accs, label='Test')
plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')
plt.title('Student Model Accuracy')
plt.legend()
plt.grid()

plt.tight_layout()
plt.show()